### ISSUE TITLE
[FIX] Resize hitbox Player or Make wider door

### ISSUE THREAD

**Issue by AllanCerveaux** [AllanCerveaux/Old-Procedural-Dungeon#6]
Vous avez le choix de : 
- Réduire la hitbox du player pour qu'il puisse passer sans soucie au niveau des portes
- Augmenter la tailles des portes de pour chaque salle

**Comment by Djohn12** [comment]
This issue should be closed, [de90c02](https://github.com/AllanCerveaux/Procedural-Dungeon/commit/de90c02975bfa61818e8d0a7807909791757329c) is supposed to have resolved the problem (merged in PR #29)
